### ISSUE TITLE
Publish Docker image

### ISSUE THREAD

**Issue by wendorf** [atlassian/escalator#114]
Thanks for making this! I'd love to be able to pull a canonical image, especially tagged with a release number, rather than building the image myself. Is that planned?

**Comment by awprice** [comment]
Thanks for opening this ticket, I'll use it as the place to track progress on getting this done. It's not on the planned features/roadmap, but I agree it is something that should be available.

**Comment by awprice** [comment]
@wendorf Awesome to see that PR! I've got the work scheduled to setup the process for publishing a docker image in my current sprint and should be ready within 2 weeks. Thanks for your patience!

**Comment by awprice** [comment]
@wendorf I've got the Docker hub repo setup to automatically build images on pushes to master and new tags - https://hub.docker.com/r/atlassian/escalator/. 

I've tagged v1.0.0 - https://github.com/atlassian/escalator/releases/tag/v1.0.0. 
`:latest` will always be the latest commit on master.
