### ISSUE TITLE
Support autodiscovery via ASG labels

### ISSUE THREAD

**Issue by wendorf** [atlassian/escalator#121]
We currently have to define autoscaling group sizes in two places: Once when creating the actual ASG, and once when configuring escalator. It would be nice if escalator could, given the name of the ASG it should be managing, find the max and min sizes. We've had situations in the past where we update the sizes in one place and not the other, which is easy to do since ASG configuration and Kubernetes deployment configuration usually lives in pretty different places.

The most important use case for us is to have autodiscovery of cluster size, but having autodiscovery of all configuration would be really cool.

**Comment by awprice** [comment]
I've just merged #124 which adds support for discovering the ASG min + max settings on start up. 

Once we are happy with how this is running, I can look at performing the discovery every time Escalator does it's run. This way we can modify  the ASG settings on the fly without worrying about updating Escalator.

**Comment by Jacobious52** [comment]
This was fixed and closed in #144
