### ISSUE TITLE
ASG minSize

### ISSUE THREAD

**Issue by skydiator** [atlassian/escalator#143]
Hi,

Is there a reason why ASG minSize cannot be 0?

We have a use case of having ASGs with 0 node and scale up only when a job scheduled to that specific ASG. This help us reduce the cost of using high performance instances, so we pay only when needed.

If no objection, I can send in a PR with our changes.

Thanks

**Comment by ShmayaFrankel** [comment]
Escalator does not support asg with the size of 0




On 11 February 2019 at 20:47:50, Skydiator (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi,

Is there a reason why ASG minSize cannot be 0?

We have a use case of having ASGs with 0 node and scale up only when a job scheduled to that specific ASG. This help us reduce the cost of using high performance instances, so we pay only when needed.

If no objection, I can send in a PR with our changes.

Thanks

**Comment by skydiator** [comment]
@ShmayaFrankel , thanks for your reply. I know it doesn't  but I want to know the reason behind it. I've modified Escalator to support ASG with 0 size. If this violates the implementation design then I don't bother sending in the MR. Thanks.

**Comment by Jacobious52** [comment]
Hi @skydiator, glad to hear that you've been using Escalator!

Scaling down the ASG to a size of 0 is a planned feature for our use case as well. We are currently looking into it, and definitely welcome your pull request to scale down to an ASG of 0.

**Comment by skydiator** [comment]
Escalator is awesome! ATM, I'm doing more testing with the changes. So far so good, will send in the PR as soon as I've done my testings.

**Comment by Jacobious52** [comment]
Hi @skydiator, just wondering if you have any update on the PR for this? If you have any questions or problems, feel free to ask here and we'll try help best we can.

**Comment by skydiator** [comment]
Created a PR for this. [PR-148](https://github.com/atlassian/escalator/pull/148)

**Comment by Jacobious52** [comment]
Completed in #155
