### ISSUE TITLE
Min_nodes & Max_nodes out of sync.

### ISSUE THREAD

**Issue by skydiator** [atlassian/escalator#145]
Hi,

During our testing, the Min_nodes & Max_nodes can be out of sync if the ASG gets updated via the AWS console or through API.

Steps to reproduce:
1. Provision Escalator with auto discovery.
2. Go to AWS console change the min nodes setting.
3. The value for Min_nodes & Max_nodes seems to be always same as the Controller first initialized.

I've created a PR to address this issue: [144](https://github.com/atlassian/escalator/pull/144)

Cheers,
Steve

**Comment by Jacobious52** [comment]
Closed by PR #144
