### ISSUE TITLE
Update Escalator to use Go 1.12.9

### ISSUE THREAD

**Issue by Jacobious52** [atlassian/escalator#150]
Go 1.12.x has been released for a while. Since Go 1.10.x support has been removed from Escalator we should add Go 1.12.x support

**Comment by Jacobious52** [comment]
We should bump to the latest version of 1.12 to mitigate the new CVEs

**Comment by youngnick** [comment]
Needs to be at least 1.12.8 to get the fixes, but 1.12.9 came out today, so you may want to go to that. ;)
