### ISSUE TITLE
Need aws-go-sdk version updated to support iam:AssumeRoleWithWebIdentity at EKS

### ISSUE THREAD

**Issue by hippothewild** [atlassian/escalator#179]
Hi, I've been using Escalator so far for scaling k8s clusters with Spark batch jobs running inside. Thanks for building an awesome product!

I'm currently running Kubernetes cluster with Kops+[Kiam](https://github.com/uswitch/kiam) which do not have any issue about assuming IAM role for Escalator pod, but when I try to run Escalator on EKS-managed cluster, it can't assume IAM role given by service account.

The root cause is that older version of AWS SDK does not support iam:AssumeRoleWithWebIdentity with OIDC provider. it seems resolvable when we update AWS SDK to the latest version - [1.23.13](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html) is the minimum verison required.

It will be greatly appreciated if the new version with updated SDK is released. Thank you so much!

**Comment by awprice** [comment]
Thanks for raising this issue @hippothewild! This is perfectly doable.

**Comment by hippothewild** [comment]
Just opened a PR to handle this issue.
