### ISSUE TITLE
Small Typo in nodegroup.md

### ISSUE THREAD

**Issue by tyg03485** [atlassian/escalator#181]
https://github.com/atlassian/escalator/blob/master/docs/configuration/nodegroup.md#taint_lower_capacity_threshold_percent

"If the node group utilisation is 5%, and taint_upper_capacity_threshold_percent is configured as 10, Escalator will taint nodes at the rate defined in fast_node_removal_rate"

should be

"If the node group utilisation is 5%, and **taint_lower_capacity_threshold_percent** is configured as 10, Escalator will taint nodes at the rate defined in fast_node_removal_rate"

ps. Thanks for providing this as open source.

**Comment by awprice** [comment]
Thanks for finding this typo! Are you able to raise a PR to fix this?
