### ISSUE TITLE
Add AWS EC2 Spot capability

### ISSUE THREAD

**Issue by haugenj** [atlassian/escalator#183]
Howdy! 👋

My name's Jason, I work for AWS down in Austin, TX. We would like to add EC2 Spot support to Escalator to expand customers' options when using AWS as the cloud provider. If you're unfamiliar with Spot, it's a different purchasing model for EC2 instances that can give up to a 90% discount rate on instance pricing, with the compromise of possibly being interrupted. Here's some official [documentation](https://aws.amazon.com/ec2/spot/).

Our proposed design would follow the same path as the current On Demand path, using [setASGDesiredSizeOneShot](https://github.com/atlassian/escalator/blob/master/pkg/cloudprovider/aws/aws.go#L345) to request instances. To enable Spot we would:

- Add SpotOptions to the setASGDesiredSizeOneShot method in a similar fashion to the existing OnDemandOptions
- Add a new parameter to the aws section of the [node_groups config](https://github.com/atlassian/escalator/blob/master/docs/configuration/nodegroup.md) called 'lifecycle' with accepted values 'spot' and 'ondemand' to designate the request as a Spot or On Demand request. We would default to using On Demand when lifecycle isn't provided to keep backwards compatibility. 
- Add another new parameter to the aws section called 'instance_types' that takes a list of different instance types (c3.large, m4.medium, etc.). Following the create fleet api, we'll use this as Overrides to the [LaunchTemplateConfigs](https://github.com/atlassian/escalator/blob/master/pkg/cloudprovider/aws/aws.go#L358) to increase the chances of a successful Spot request. We would keep the single instance type requirement as it is currently.
- Add tests as necessary to cover all new Spot use cases

Let me know what you think, we're excited to get working on this!

\- Jason

**Comment by awprice** [comment]
Thanks for raising this @haugenj! This request sounds perfectly reasonable and we look forward to your PR. +1 on keeping the backwards compatibility and default behaviour the same.
