### ISSUE TITLE
[BUG] Docker push action failing

### ISSUE THREAD

**Issue by awprice** [atlassian/escalator#219]
**Describe the bug**
The Docker push action is currently failing, even though it is able to successfully push the images to the Github container registry.

**To Reproduce**
Run the Docker action on master

**Expected behavior**
For the Docker push action to not fail even if it does successfully push the image.

**Screenshots or Logs**
https://github.com/atlassian/escalator/actions/runs/4485895033/jobs/7887883086

**Kubernetes Cluster Version**
N/A

**Escalator Version**
N/A

**Additional context**
N/A

**Comment by awprice** [comment]
@hligit I think you might have worked on the Docker push action/workflow recently, would you happen to know what is happening?

**Comment by hligit** [comment]
Probably a breaking change with the buildx setup action. The [doc]( https://github.com/docker/setup-buildx-action) is using v2 now.
