### ISSUE TITLE
Implement healthcheck endpoint

### ISSUE THREAD

**Issue by awprice** [atlassian/escalator#57]
Implement healthcheck endpoint to respond with the health of Escalator.

Should perform perform the following checks internally:
- Whether the cloud provider session can list/describe node groups in the cloud provider
- Whether it can list pods/nodes on the apiserver (depends on how long this takes and whether it is taxing)

**Comment by youngnick** [comment]
The current pattern Escalator is using is that it will crash itself on any error and rely on Kubernetes to restart it. Persistent problems should then be caught by watching the deployment for Pods in CrashLoopBackoff state.
Closing this won't out as 'Won't Do'.
