### ISSUE TITLE
Add additional metrics

### ISSUE THREAD

**Issue by awprice** [atlassian/escalator#60]
Add some additional Prometheus metrics, for example:
- [x] Whether the scaling lock is present
- [x] Time that the scaling lock has been present for
- [x] Time taken for new nodes to be created to be ready in Kubernetes
- [ ] Time after node has been tainted until it was terminated
- [x] Current state (scaling up/doing nothing/scaling down), this could also just be the Node Delta value (negative, zero, positive)
- [x] ASG metrics (current ASG size, desired ASG size)

**Comment by Jacobious52** [comment]
Closing as I think this is done and no recent movement
